name: pester
on: pull_request

jobs:
  nuke-with-logging:
    name: ./build.sh ExecuteTestsFixLogging
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - name: Install Pester
      #   run: Install-Module -Name Pester -Force
      - name: Invoke-Pester
        run: ./build.sh ExecuteTestsFixLogging
  nuke-without-logging:
    name: ./build.sh ExecuteTests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - name: Install Pester
      #   run: Install-Module -Name Pester -Force
      - name: Invoke-Pester
        run: ./build.sh ExecuteTests
